/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_paulniu_jni_demo_JNIUtil */

#ifndef _Included_com_paulniu_jni_demo_JNIUtil
#define _Included_com_paulniu_jni_demo_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_paulniu_jni_demo_JNIUtil
 * Method:    getResult
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_paulniu_jni_1demo_JNIUtil_getResult
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
